### ISSUE TITLE
Inkscape 1.0

### ISSUE THREAD

**Issue by pknoot** [THX2112/Eurorack-Panel-Designer#7]
Inkscape 1.0 broke some old extensions.  Will the Panel Designer still work?

**Comment by Neon22** [comment]
Has now been updated and a pull request generated. 
You can find the 1.0 version on my fork here:
- https://github.com/Neon22/Eurorack-Panel-Designer

**Comment by Neon22** [comment]
Published;
- https://inkscape.org/~Neon22/%E2%98%85inkscape-eurorack

**Comment by THX2112** [comment]
Everything merged fine and now updated.

Thanks Neon22!
